export const casualTopics: string[] = [
  // Daily life
  "Tell us about what you did today",
  "Describe your morning routine",
  "What is your favorite time of day and why?",
  "Tell us about something funny that happened to you",
  "Describe a typical day in your life",
  "What do you like to do after school?",
  "Tell us about your bedtime routine",
  "What do you do on a rainy day?",
  "Describe your favorite weekend activity",
  "Tell us about something you learned recently",

  // Favorites
  "What is your favorite food and why?",
  "Tell us about your favorite movie or show",
  "What is your favorite book and what is it about?",
  "Describe your favorite game to play",
  "What is your favorite season and why?",
  "Tell us about your favorite song",
  "What is your favorite holiday and why?",
  "Describe your favorite outfit",
  "What is your favorite sport or activity?",
  "Tell us about your favorite toy or possession",

  // Imagination
  "If you could have any superpower, what would it be and why?",
  "If you could be any animal for a day, what would you pick?",
  "If you could travel anywhere in the world, where would you go?",
  "If you could invent something new, what would it be?",
  "If you had a magic wand, what would you do with it?",
  "If you could meet any fictional character, who would it be?",
  "If you could live in any time period, when would you choose?",
  "If you could fly, where would you go first?",
  "If you had a time machine, where would you travel?",
  "If you could be invisible for a day, what would you do?",

  // Family & friends
  "Tell us about your best friend",
  "Describe something fun you have done with your family",
  "Tell us about a person you look up to",
  "What do you love most about your family?",
  "Describe a funny memory with a sibling or cousin",
  "Tell us about a time a friend made you feel better",
  "What makes someone a good friend?",
  "Tell us about a family tradition you enjoy",
  "Describe your favorite thing to do with your friends",
  "Tell us about someone who has taught you something important",

  // School
  "What is your favorite subject at school and why?",
  "Describe your favorite school memory",
  "Tell us about your favorite teacher and what makes them special",
  "What is the hardest thing about school?",
  "Tell us about a project at school you are proud of",
  "Describe your favorite part of the school day",
  "What do you wish you could learn more about at school?",
  "Tell us about a time you helped a classmate",
  "What is your favorite school lunch?",
  "Describe what your dream classroom would look like",

  // Nature & animals
  "Describe your favorite animal",
  "What is the most interesting bug or insect you have seen?",
  "Tell us about your favorite outdoor place",
  "Describe a time you saw something amazing in nature",
  "If you could have any pet, what would you choose and why?",
  "Tell us about your favorite plant or flower",
  "Describe what you see outside your window",
  "What is your favorite thing about the ocean?",
  "Tell us about an animal you would like to learn more about",
  "Describe your perfect outdoor adventure",

  // Dreams & goals
  "What do you want to be when you grow up?",
  "Tell us about a goal you have for this year",
  "Describe something you really want to learn how to do",
  "What would you do if you were in charge for a day?",
  "Tell us about a dream you had while sleeping",
  "Describe what your life might look like in ten years",
  "What is one thing you want to accomplish before your next birthday?",
  "Tell us about something you used to want that changed",
  "What job would you never want to do and why?",
  "Describe your perfect future home",

  // Holidays & events
  "Describe your best birthday party",
  "Tell us about your favorite holiday celebration",
  "Describe the best gift you have ever received",
  "Tell us about the best gift you have ever given someone",
  "Describe a special event you are looking forward to",
  "Tell us about a holiday tradition you love",
  "Describe the most fun party you have ever been to",
  "Tell us about your favorite thing to do during summer break",
  "Describe a special trip you have taken with your family",
  "Tell us about the best day of this past year",

  // Food
  "If you could eat anything for dinner, what would you pick?",
  "Tell us how to make your favorite snack",
  "Describe the best meal you have ever eaten",
  "If you could add a new flavor of ice cream, what would it be?",
  "Tell us about a food you did not like but now enjoy",
  "Describe your perfect pizza",
  "If you ran a restaurant, what would you serve?",
  "Tell us about a food that reminds you of a happy memory",
  "Describe the weirdest food combination you have tried",
  "If you could only eat one food for a week, what would you choose?",

  // Places
  "Describe your favorite place to visit",
  "Tell us about your bedroom and why it is special to you",
  "Describe the best playground you have ever been to",
  "If you could build your dream treehouse, what would it look like?",
  "Tell us about a place you have always wanted to visit",
  "Describe your neighborhood",
  "Tell us about your favorite room in your house",
  "Describe the coolest building or place you have ever seen",
  "If you could design a theme park, what would be in it?",
  "Tell us about a place that makes you feel happy and calm",
];
