export type SparDifficulty = "easy" | "medium" | "hard";

export const sparTopics: Record<SparDifficulty, string[]> = {
  easy: [
    // Simple, concrete, fun — 3rd & 4th grade level
    "Dogs are better pets than cats.",
    "School should start later in the morning.",
    "Kids should get more recess time.",
    "Homework should be banned.",
    "School uniforms should be required.",
    "Video games are good for you.",
    "Summer is better than winter.",
    "Chocolate ice cream is better than vanilla.",
    "Reading is better than watching TV.",
    "Every classroom should have a class pet.",
    "School lunches should always be free.",
    "Kids should be allowed to use phones at school.",
    "Pizza is the best food.",
    "Outdoor recess is better than indoor recess.",
    "Kids should choose their own bedtime.",
    "Physical education should be every day.",
    "Libraries are better than the internet for learning.",
    "Playing outside is better than playing video games.",
    "Every student should have their own tablet.",
    "Art class is just as important as math.",
    "Schools should teach cooking.",
    "Cats are smarter than dogs.",
    "A shorter school year would be better for students.",
    "Superheroes are better than regular heroes.",
    "Having a sibling is better than being an only child.",
    "Field trips should happen every month.",
    "Juice is healthier than soda.",
    "Students should be able to pick their own seats in class.",
    "Every home should have a pet.",
    "Children should not be allowed to drink soda.",
    "New York is better than California.",
    "Northern California is better than Southern California.",
    "Summer vacation should be longer.",
    "Children should wear uniforms to school.",
    "Kids should be allowed to have cell phones.",
    "Television is better than books.",
    "Teachers assign too much homework.",
    "Television is a bad influence for kids.",
  ],

  medium: [
    // Requires simple reasoning and some examples — 5th & 6th grade level
    "Cell phones should be banned in schools.",
    "Year-round school is better than summer break.",
    "Students should be allowed to grade their teachers.",
    "All students should be required to volunteer in the community.",
    "Social media does more harm than good for kids.",
    "All students should learn a second language.",
    "Junk food should not be sold in schools.",
    "Students should wear uniforms in middle school.",
    "Zoos are harmful to animals.",
    "Online school is better than in-person school.",
    "Students should be allowed to use calculators on all math tests.",
    "Every student should participate in a sport.",
    "Television teaches more than it harms.",
    "Standardized tests should be abolished.",
    "It is more important to be kind than to be honest.",
    "Community service should be required to graduate.",
    "Violent video games should not be sold to kids.",
    "Parents should limit screen time for children.",
    "Books are better than movies.",
    "It's better to have one close friend than many casual friends.",
    "Being creative is more important than being smart.",
    "Students should have a say in what they learn in school.",
    "Technology makes us less social.",
    "Failure is a better teacher than success.",
    "Sports build character.",
    "It's okay to lie if it protects someone's feelings.",
    "School days should be shorter.",
    "Every student should learn basic coding.",
    "Public transportation should be free for students.",
    "Peer pressure can sometimes be a good thing.",
    "Social networking sites are bad.",
    "Kids should be allowed to purchase anything with their allowance, as long as it is legal.",
    "Parents should be punished for their kids' mistakes.",
    "Peer pressure can be a good thing.",
    "Brains get you further in life than beauty.",
    "Lying can be moral.",
    "All junk food should be banned from schools.",
    "School hours should be changed to 12 p.m. to 6 p.m.",
    "Private school is better than public school.",
    "All students should get to choose half their classes.",
    "Computers should replace teachers.",
    "Football should be banned from school sports.",
    "Every student should play a musical instrument.",
    "Year-round education is better for students.",
    "PE should be required of all students throughout middle and high school.",
    "All schoolwork should be paperless.",
    "The Internet should be banned from schools.",
    "All parents should be required to attend parenting classes.",
    "All students should be required to learn a foreign language in middle school.",
    "Zoos should be abolished.",
    "Statewide tests should be abolished.",
    "Play is more important than work.",
    "Technology does more harm than good.",
    "All students should be required to take a cooking class.",
    "Teachers should require homework.",
    "It's better to be poor with many friends than to be rich with no friends.",
    "Children are smarter than their parents.",
    "Fashion is more important than function.",
    "The pen is mightier than the sword.",
    "Strict teachers are better than lenient teachers.",
    "It is better to be brave than cautious.",
    "Studying alone is better than in groups.",
    "It is better to have many friends than one best friend.",
    "Physical education should be required in schools.",
    "Students should be required to learn a foreign language.",
    "Technology is good for the classroom.",
    "It is more important to be honest than to be kind.",
    "It is better to be confident than humble.",
    "Art in school is as important as science.",
    "Should community service be required for graduation?",
  ],

  hard: [
    // Abstract, policy, or ethical — 7th grade and above
    "The death penalty should be abolished.",
    "Animal testing should be illegal.",
    "The voting age should be lowered to 16.",
    "Social media companies should be regulated by the government.",
    "Healthcare should be free for everyone.",
    "Climate change is the greatest threat of our time.",
    "Artificial intelligence will do more harm than good.",
    "Privacy is more important than national security.",
    "It is sometimes right to break the law.",
    "Wealth inequality is the most important problem to solve today.",
    "Democracy is the best form of government.",
    "The benefits of globalization outweigh its costs.",
    "Nations have a moral obligation to accept refugees.",
    "Gene editing in humans should be permitted.",
    "Governments should have the right to monitor citizens' online activity.",
    "Cancel culture does more harm than good.",
    "Space exploration should be funded over solving problems on Earth.",
    "Capitalism is the best economic system.",
    "Human cloning should be banned.",
    "It is more important to fund education than the military.",
    "The ends justify the means.",
    "Free speech should have limits.",
    "Compulsory voting should be introduced.",
    "Single-use plastics should be banned worldwide.",
    "Religion should not influence government policy.",
    "Religion should be taught in school.",
    "Privacy should be a right.",
    "Oil and coal are a bigger threat than nuclear weapons.",
    "It is morally acceptable to steal.",
    "Walt Disney has done better for humanity than William Shakespeare.",
    "Breaking the law is okay if you are protesting.",
    "The voting age should be decreased to 15.",
    "Animal testing should be legal.",
    "The Olympics should always be held in Greece.",
    "The death penalty should be banned.",
    "Humans should explore space.",
    "Using the atomic bomb is never justified.",
    "All people should be vegetarians.",
    "Solar energy should replace all traditional forms of energy.",
    "The moon should be colonized.",
    "Security is more important than freedom.",
    "It is sometimes right for the government to restrict freedom of speech.",
    "It is more important to fund space exploration than social services.",
    "Humans are becoming the most dangerous animals on the planet.",
    "Government should provide housing for everyone.",
    "Single-use plastic should be banned.",
    "Children should have the right to vote.",
    "Humans should try to live forever.",
  ],
};

export function getTopicsByDifficulty(difficulty: SparDifficulty): string[] {
  return sparTopics[difficulty];
}
