export type SparDifficulty = "easy" | "medium" | "hard";

export const sparTopics: Record<SparDifficulty, string[]> = {
  easy: [
    // Simple, concrete, fun — 3rd & 4th grade level
    "Dogs are better pets than cats.",
    "School should start later in the morning.",
    "Kids should get more recess time.",
    "Homework should be banned.",
    "School uniforms should be required.",
    "Video games are good for you.",
    "Summer is better than winter.",
    "Chocolate ice cream is better than vanilla.",
    "Reading is better than watching TV.",
    "Every classroom should have a class pet.",
    "School lunches should always be free.",
    "Kids should be allowed to use phones at school.",
    "Pizza is the best food.",
    "Outdoor recess is better than indoor recess.",
    "Kids should choose their own bedtime.",
    "Physical education should be every day.",
    "Libraries are better than the internet for learning.",
    "Playing outside is better than playing video games.",
    "Every student should have their own tablet.",
    "Art class is just as important as math.",
    "Schools should teach cooking.",
    "Cats are smarter than dogs.",
    "A shorter school year would be better for students.",
    "Superheroes are better than regular heroes.",
    "Having a sibling is better than being an only child.",
    "Field trips should happen every month.",
    "Juice is healthier than soda.",
    "Students should be able to pick their own seats in class.",
  ],

  medium: [
    // Requires simple reasoning and some examples — 5th & 6th grade level
    "Cell phones should be banned in schools.",
    "Year-round school is better than summer break.",
    "Students should be allowed to grade their teachers.",
    "All students should be required to volunteer in the community.",
    "Social media does more harm than good for kids.",
    "All students should learn a second language.",
    "Junk food should not be sold in schools.",
    "Students should wear uniforms in middle school.",
    "Zoos are harmful to animals.",
    "Online school is better than in-person school.",
    "Students should be allowed to use calculators on all math tests.",
    "Every student should participate in a sport.",
    "Television teaches more than it harms.",
    "Standardized tests should be abolished.",
    "It is more important to be kind than to be honest.",
    "Community service should be required to graduate.",
    "Violent video games should not be sold to kids.",
    "Parents should limit screen time for children.",
    "Books are better than movies.",
    "It's better to have one close friend than many casual friends.",
    "Being creative is more important than being smart.",
    "Students should have a say in what they learn in school.",
    "Technology makes us less social.",
    "Failure is a better teacher than success.",
    "Sports build character.",
    "It's okay to lie if it protects someone's feelings.",
    "School days should be shorter.",
    "Every student should learn basic coding.",
    "Public transportation should be free for students.",
    "Peer pressure can sometimes be a good thing.",
  ],

  hard: [
    // Abstract, policy, or ethical — 7th grade and above
    "The death penalty should be abolished.",
    "Animal testing should be illegal.",
    "The voting age should be lowered to 16.",
    "Social media companies should be regulated by the government.",
    "Healthcare should be free for everyone.",
    "Climate change is the greatest threat of our time.",
    "Artificial intelligence will do more harm than good.",
    "Privacy is more important than national security.",
    "It is sometimes right to break the law.",
    "Wealth inequality is the most important problem to solve today.",
    "Democracy is the best form of government.",
    "The benefits of globalization outweigh its costs.",
    "Nations have a moral obligation to accept refugees.",
    "Gene editing in humans should be permitted.",
    "Governments should have the right to monitor citizens' online activity.",
    "Cancel culture does more harm than good.",
    "Space exploration should be funded over solving problems on Earth.",
    "Capitalism is the best economic system.",
    "Human cloning should be banned.",
    "It is more important to fund education than the military.",
    "The ends justify the means.",
    "Free speech should have limits.",
    "Compulsory voting should be introduced.",
    "Single-use plastics should be banned worldwide.",
    "Religion should not influence government policy.",
  ],
};

export function getTopicsByDifficulty(difficulty: SparDifficulty): string[] {
  return sparTopics[difficulty];
}
