export interface TongueTwister {
  text: string;
  difficulty: "easy" | "medium" | "hard";
}

export const tongueTwisters: TongueTwister[] = [
  // ── Easy ──────────────────────────────────────────────────────────────────
  { text: "She sees cheese.", difficulty: "easy" },
  { text: "She sells seashells by the seashore.", difficulty: "easy" },
  { text: "The blue bluebird blinks.", difficulty: "easy" },
  { text: "He threw three free throws.", difficulty: "easy" },
  { text: "Eleven benevolent elephants.", difficulty: "easy" },
  { text: "Nine nimble noblemen nibbling nuts.", difficulty: "easy" },
  { text: "Betty and Bob brought back blue balloons from the big bazaar.", difficulty: "easy" },
  { text: "Really leery, rarely Larry.", difficulty: "easy" },
  { text: "Scissors sizzle, thistles sizzle.", difficulty: "easy" },
  { text: "Kitty caught the kitten in the kitchen.", difficulty: "easy" },
  { text: "Clean clams crammed in clean cans.", difficulty: "easy" },
  { text: "Five frantic frogs fled from fifty fierce fishes.", difficulty: "easy" },
  { text: "Wayne went to Wales to watch walruses.", difficulty: "easy" },
  { text: "Six sleek swans swam swiftly southwards.", difficulty: "easy" },
  { text: "The great Greek grape growers grow great Greek grapes.", difficulty: "easy" },
  { text: "Busy buzzing bumblebees.", difficulty: "easy" },
  { text: "Friendly fleas and fireflies.", difficulty: "easy" },
  { text: "Splish, splash, splosh, went the dog in the wash.", difficulty: "easy" },
  { text: "Two tried and true tridents.", difficulty: "easy" },
  { text: "Great glass globes glow greenly.", difficulty: "easy" },
  { text: "Rubber rudders bounce.", difficulty: "easy" },
  { text: "A happy hippo hopped and hiccupped.", difficulty: "easy" },
  { text: "Six sticky skeletons.", difficulty: "easy" },
  { text: "Proper copper coffee pot.", difficulty: "easy" },
  { text: "Zebras zig and zebras zag.", difficulty: "easy" },
  { text: "Willie's really weary.", difficulty: "easy" },
  { text: "Red leather, yellow leather.", difficulty: "easy" },
  { text: "Bad money, mad bunny.", difficulty: "easy" },
  { text: "Freshly-fried flying fish.", difficulty: "easy" },
  { text: "Red lorry, yellow lorry.", difficulty: "easy" },
  { text: "Selfish shellfish.", difficulty: "easy" },
  { text: "She threw three balls.", difficulty: "easy" },
  { text: "Six slippery snails slid slowly seaward.", difficulty: "easy" },
  { text: "Dark dusty disks.", difficulty: "easy" },
  { text: "I like New York, unique New York, I like unique New York.", difficulty: "easy" },
  { text: "Fuzzy Wuzzy was a bear. Fuzzy Wuzzy had no hair.", difficulty: "easy" },
  { text: "Twelve twins twirled twelve twigs.", difficulty: "easy" },
  { text: "I saw Susie sitting in a shoeshine shop.", difficulty: "easy" },
  { text: "Four fine fresh fish for you.", difficulty: "easy" },
  { text: "Which witch wished which wicked wish?", difficulty: "easy" },
  { text: "A snake sneaks to seek a snack.", difficulty: "easy" },
  { text: "A proper cup of coffee from a proper copper coffee pot.", difficulty: "easy" },
  { text: "Two tiny tigers take two taxis to town.", difficulty: "easy" },
  { text: "An ape hates grape cakes.", difficulty: "easy" },
  { text: "Five fat frogs flying on fast flipping flies.", difficulty: "easy" },
  { text: "A big black bug bit a big black dog on his big black nose.", difficulty: "easy" },
  { text: "Four furious friends fought for the phone.", difficulty: "easy" },
  { text: "Rubber baby buggy bumpers.", difficulty: "easy" },
  { text: "Toy boat. Toy boat. Toy boat.", difficulty: "easy" },
  { text: "Black bug's blood.", difficulty: "easy" },
  { text: "Sheep should sleep in a shed.", difficulty: "easy" },
  { text: "Unique New York.", difficulty: "easy" },
  { text: "Pre-shrunk silk shirts.", difficulty: "easy" },
  { text: "Flash message.", difficulty: "easy" },
  { text: "Thin sticks, thick bricks.", difficulty: "easy" },
  { text: "Knit kitten. Knit kitten. Knit kitten.", difficulty: "easy" },
  { text: "Cheap ship trip.", difficulty: "easy" },
  { text: "Mix a box of mixed biscuits.", difficulty: "easy" },
  { text: "Cooks cook cupcakes quickly.", difficulty: "easy" },
  { text: "Drew Dodd's dad's dog's dead.", difficulty: "easy" },
  { text: "Brisk brave brigadiers.", difficulty: "easy" },
  { text: "Chop shops stock chops.", difficulty: "easy" },

  // ── Medium ────────────────────────────────────────────────────────────────
  { text: "Birdie birdie in the sky laid a turdie in my eye. If cows could fly I'd have a cow pie in my eye.", difficulty: "medium" },
  { text: "A big bug bit the little beetle but the little beetle bit the big bug back.", difficulty: "medium" },
  { text: "How many yaks could a yak pack, pack if a yak pack could pack yaks?", difficulty: "medium" },
  { text: "Double bubble gum, bubbles double.", difficulty: "medium" },
  { text: "Gobbling gargoyles gobbled gobbling goblins.", difficulty: "medium" },
  { text: "A big black bear sat on a big black rug.", difficulty: "medium" },
  { text: "If two witches would watch two watches, which witch would watch which watch?", difficulty: "medium" },
  { text: "If a dog chews shoes, whose shoes does he choose?", difficulty: "medium" },
  { text: "I saw a saw that could saw out any other saw I ever saw.", difficulty: "medium" },
  { text: "Nine nice night nurses nursing nicely.", difficulty: "medium" },
  { text: "Picky people pick Peter Pan Peanut-Butter, 'tis the peanut-butter picky people pick.", difficulty: "medium" },
  { text: "Babbling baby boys blurted boldly.", difficulty: "medium" },
  { text: "The two-toed tree-toad tried to win the three-toed she-toad's heart.", difficulty: "medium" },
  { text: "Six sick hicks nick six slick bricks with picks and sticks.", difficulty: "medium" },
  { text: "I slit the sheet, the sheet I slit, and on the slitted sheet, I sit.", difficulty: "medium" },
  { text: "Give papa a cup of proper coffee in a copper coffee cup.", difficulty: "medium" },
  { text: "Denise sees the fleece, Denise sees the fleas. At least Denise could sneeze and feed and freeze the fleas.", difficulty: "medium" },
  { text: "I scream, you scream, we all scream for ice cream!", difficulty: "medium" },
  { text: "Round and round the rugged rock the ragged rascal ran.", difficulty: "medium" },
  { text: "How can a clam cram in a clean cream can?", difficulty: "medium" },
  { text: "She sold six shabby-sheared sheep on ship.", difficulty: "medium" },
  { text: "The top cop saw a cop top.", difficulty: "medium" },
  { text: "Fred fed Ted bread and Ted fed Fred bread.", difficulty: "medium" },
  { text: "Seven slippery seals silently slid down the slippery seaweed.", difficulty: "medium" },
  { text: "How much wood would a woodchuck chuck if a woodchuck could chuck wood?", difficulty: "medium" },
  { text: "Fuzzy Wuzzy was a bear. Fuzzy Wuzzy had no hair. Fuzzy Wuzzy wasn't very fuzzy, was he?", difficulty: "medium" },
  { text: "Peter Piper picked a peck of pickled peppers. How many pickled peppers did Peter Piper pick?", difficulty: "medium" },
  { text: "Three thin thinkers thinking thick thoughtful thoughts.", difficulty: "medium" },
  { text: "Three grey geese in the green grass grazing. Gray were the geese and green was the grass.", difficulty: "medium" },
  { text: "Many mumbling mice are making midnight music in the moonlight, mighty nice.", difficulty: "medium" },
  { text: "I can think of six thin things, but I can think of six thick things too.", difficulty: "medium" },
  { text: "One smart fellow, he felt smart. Two smart fellows, they felt smart. Three smart fellows, they all felt smart.", difficulty: "medium" },
  { text: "A flea and a fly flew up in a flue. Said the flea, \"Let us fly!\" Said the fly, \"Let us flee!\" So they flew through a flaw in the flue.", difficulty: "medium" },
  { text: "If two witches were watching two watches, which witch would watch which watch?", difficulty: "medium" },
  { text: "Eddie edited it.", difficulty: "medium" },
  { text: "How much caramel can a cannon ball cannon?", difficulty: "medium" },
  { text: "Santa's short suit shrunk.", difficulty: "medium" },
  { text: "She stood on the balcony, inexplicably mimicking him hiccupping.", difficulty: "medium" },
  { text: "Can you can a can as a canner can can a can?", difficulty: "medium" },
  { text: "Theo thrust a thumb through the thick of his thumb.", difficulty: "medium" },
  { text: "Crush grapes, grapes crush, crush grapes.", difficulty: "medium" },
  { text: "Green glass globes glow greenly.", difficulty: "medium" },
  { text: "Excited executors executing the will expertly.", difficulty: "medium" },
  { text: "The soldier's shoulder shuddered when she shifted the shelf.", difficulty: "medium" },
  { text: "Knife and a fork, bottle and a cork, that is the way you spell New York.", difficulty: "medium" },
  { text: "Soldiers' shoulders shudder when silly shenanigans shower shards.", difficulty: "medium" },

  // ── Hard ──────────────────────────────────────────────────────────────────
  { text: "Fresh fried fish, fish fresh fried, fried fish fresh, fish fried fresh.", difficulty: "hard" },
  { text: "Imagine an imaginary menagerie manager managing an imaginary menagerie.", difficulty: "hard" },
  { text: "Send toast to ten tense stout saints' ten tall tents.", difficulty: "hard" },
  { text: "Rory's lawn rake rarely rakes really right.", difficulty: "hard" },
  { text: "Silly Sally swiftly shooed seven silly sheep.", difficulty: "hard" },
  { text: "Rory the warrior and Roger the worrier were reared wrongly in a rural brewery.", difficulty: "hard" },
  { text: "A skunk sat on a stump and thunk the stump stunk, but the stump thunk the skunk stunk.", difficulty: "hard" },
  { text: "On a lazy laser raiser lies a laser ray eraser.", difficulty: "hard" },
  { text: "Many mumbling mice are making merry music in the moonlight.", difficulty: "hard" },
  { text: "These sheep shouldn't sleep in a shack; Sheep should sleep in a shed.", difficulty: "hard" },
  { text: "Lesser leather never weathered wetter weather better.", difficulty: "hard" },
  { text: "The sixth sick sheik's sixth sheep's sick.", difficulty: "hard" },
  { text: "To begin to toboggan first buy a toboggan, but don't buy too big a toboggan. Too big a toboggan is too big a toboggan to buy to begin to toboggan.", difficulty: "hard" },
  { text: "Which wristwatches are Swiss wristwatches?", difficulty: "hard" },
  { text: "Supposed to be pink pistachio, supposed to be pistachio pink.", difficulty: "hard" },
  { text: "Seven sleazy shysters in sharkskin suits sold sheared sealskins to seasick sailors.", difficulty: "hard" },
  { text: "Thirty-three thirsty, thundering thoroughbreds thumped Mr Thurber on Thursday.", difficulty: "hard" },
  { text: "The thirty-three thieves thought that they thrilled the throne throughout Thursday.", difficulty: "hard" },
  { text: "Brisk brave brigadiers brandished broad bright blades, blunderbusses, and bludgeons—balancing them badly.", difficulty: "hard" },
  { text: "How much ground would a groundhog hog, if a groundhog could hog ground? A groundhog would hog all the ground he could hog if a groundhog could hog ground.", difficulty: "hard" },
  { text: "Betty Botter bought some butter but, she said, this butter's bitter; if I put it in my batter, it will make my batter bitter. But, a bit of better butter will make my batter better.", difficulty: "hard" },
  { text: "I saw Susie sitting in a shoe shine shop. Where she shines, she sits, and where she sits, she shines.", difficulty: "hard" },
  { text: "She sells seashells by the seashore. The shells she sells are seashells, I'm sure. So if she sells seashells on the seashore, then I'm sure she sells seashore shells.", difficulty: "hard" },
  { text: "Whether the weather be fine or whether the weather be not, whether the weather be cold or whether the weather be hot, we'll weather the weather whatever the weather, whether we like it or not.", difficulty: "hard" },
  { text: "How much wood would a woodchuck chuck, if a woodchuck could chuck wood? A woodchuck would chuck as much wood as a woodchuck would if a woodchuck could chuck wood.", difficulty: "hard" },
  { text: "If you must cross a course cross cow across a crowded cow crossing, cross the cross coarse cow across the crowded cow crossing carefully.", difficulty: "hard" },
  { text: "A tutor who tooted the flute tried to teach two young tooters to toot. Said the two to the tutor, \"Is it harder to toot, or to tutor two tooters to toot?\"", difficulty: "hard" },
  { text: "Peter Piper picked a peck of pickled peppers. A peck of pickled peppers Peter Piper picked. If Peter Piper picked a peck of pickled peppers, where's the peck of pickled peppers Peter Piper picked?", difficulty: "hard" },
  { text: "Yellow butter, purple jelly, red jam, black bread. Spread it thick, say it quick! Yellow butter, purple jelly, red jam, black bread. Spread it thicker, say it quicker!", difficulty: "hard" },
  { text: "Whether the weather is warm, whether the weather is hot, we have to put up with the weather, whether we like it or not.", difficulty: "hard" },
  { text: "Betty Botter bought some butter, but she said, \"This butter's bitter. If I put it in my batter, it will make my batter bitter.\"", difficulty: "hard" },
  { text: "Mr. See owned a saw, and Mr. Soar owned a seesaw. Now See's saw sawed Soar's seesaw before Soar saw See.", difficulty: "hard" },
  { text: "One-One was a racehorse; Two-Two was one, too. When One-One won one race, Two-Two won one, too.", difficulty: "hard" },
  { text: "Swan swam over the sea, swim, swan, swim! Swan swam back again, well swum, swan!", difficulty: "hard" },
  { text: "I wish to wash my Irish wristwatch.", difficulty: "hard" },
  { text: "Pad kid poured curd pulled cod.", difficulty: "hard" },
  { text: "Near an ear, a nearer ear, a nearly eerie ear.", difficulty: "hard" },
  { text: "Through three cheese trees three free fleas flew. While these fleas flew, freezy breeze blew.", difficulty: "hard" },
  { text: "Of all the felt I ever felt, I never felt a piece of felt which felt as fine as that felt felt, when first I felt that felt hat's felt.", difficulty: "hard" },
  { text: "I thought I thought of thinking of thanking you.", difficulty: "hard" },
  { text: "He thrusts his fists against the posts and still insists he sees the ghosts.", difficulty: "hard" },
  { text: "Shelly sells shells from the seashore to shell seekers seeking seashells she sells on the shore.", difficulty: "hard" },
];

export function getTwistersByDifficulty(difficulty: "easy" | "medium" | "hard"): TongueTwister[] {
  return tongueTwisters.filter(t => t.difficulty === difficulty);
}

export function getRandomTwister(difficulty: "easy" | "medium" | "hard"): TongueTwister {
  const pool = getTwistersByDifficulty(difficulty);
  return pool[Math.floor(Math.random() * pool.length)];
}
